runtime: nodejs12
env: standard
env_variables:
  MONGO_URL: mongodb+srv://eyacquah:Si_.@n4TjBYHzMy@cluster0.cmktk.mongodb.net/commercio?retryWrites=true&w=majority
  GOOGLE_CLIENT_ID: 110391433971-jlonume67c36uteleloluqdpmlhd8926.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: 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
